apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-app-rs-pvc
  labels:
    app: redis
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
