apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-app-rs-pv
  labels:
    type: local
    app: redis
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/rhp/acc-project/auth-app/.volume/rs
