apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-app-pg-pvc
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
